### ISSUE TITLE
aminofixfix.asyncfixfix.client has no attribute 'device_id

### ISSUE THREAD

**Issue by HakiBl4ck** [imperialwool/Amino.fix.fix#4]
## Environment
Linux Lite
Python 3.10
aiohttp

## Bug description
When I want to run the code it prints this on the screen, how to fix it?

**Comment by shaderw0lf** [comment]
Can you provide code?

**Comment by BogadoCA** [comment]
> Can you provide code?

i think he is using this:

import json
import time
import os
from aminofix.lib.util.helpers import gen_deviceId as device_generator

file_name = "accounts.json"
new_file = "accountsz.json"

with open(file_name) as f:
    data = json.load(f)

with open(new_file, "w") as f:
    f.write("[")
    for i, account in enumerate(data, 1):
        device_id = device_generator()
        device_key = device_id[-40:]
        email = account["email"]
        password = account["password"]
        transfer = {"email": email, "password": password, "device": device_id, "deviceKey": device_key}
        json.dump(transfer, f)
        if i != len(data):
            f.write(",\n")
        print(f"done {i}")

    f.write("]")

time.sleep(2)

**Comment by shaderw0lf** [comment]
if so, it will work

<img width="860" alt="Снимок экрана 2024-05-17 в 11 25 25" src="https://github.com/imperialwool/Amino.fix.fix/assets/55358751/63b0a244-1e72-4575-9837-d69a4dd07c11">

also there is an device_id in async client
so im waiting for code from issuer
but i found another issues

<img width="676" alt="Снимок экрана 2024-05-17 в 11 28 10" src="https://github.com/imperialwool/Amino.fix.fix/assets/55358751/67eebd13-1cdb-4c7c-83af-a172bdfd8357">

**Comment by HakiBl4ck** [comment]
this error print me:
Traceback (most recent call last):
  File "/home/max/Documents/pydocs/fixfix.py", line 8, in <module>
    sub = SubClient(mainClient=Client, comId="67")
  File "/home/max/.local/lib/python3.10/site-packages/aminofixfix/asyncfixfix/sub_client.py", line 46, in __init__
    self, deviceId=mainClient.device_id, proxies=mainClient.proxies,
AttributeError: type object 'Client' has no attribute 'device_id'

**Comment by shaderw0lf** [comment]
> sub = SubClient(mainClient=Client, comId="67")

bro you literally passed class "Client" as inited client 💀
you should do smth like

```python
# ...
client = Client(socket_enabled=False)
sub = SubClient(client, comId=67)
# ...
```

or wait for update when you can create subclients without any clients

closing issue as its not lib problem
